### ISSUE TITLE
VPN problem

### ISSUE THREAD

**Issue by tangalbert919** [gj86/synergy#1]
r19 of the Synergy kernel seems to start freaking out when a VPN connection is made.

I don't have the logs because once the device turns off the screen, it can't ever turn it back on. A hard reboot is required to get it going again.

The LineageOS stock kernel does not have this problem. Perhaps we can fix this issue?

**Comment by gj86** [comment]
Extract the _boot.img_ from kernel zip and flash it. Before doing so make sure to **dirty flash rom**. See if that fixes issue.
