### ISSUE TITLE
Microphone sensitivity

### ISSUE THREAD

**Issue by simplers2** [gj86/synergy#2]
Hi! In the original ROM the mics in the Note 3 worked flawlessly even in high volume situations like live concerts. But now, using this Kernel even people talk make the sound distort. Can you give a check on this subject? Other than that, it's been great working on this refreshed Note 3. Keep up the great work!

**Comment by gj86** [comment]
Reset any changed made to audio settings by Kernel tweaking tools. Apart from that it's not related to kernel. Also custom ROM doesn't do noise cancellation as good as compared to stock ROM.
